# Site settings
title: Wenmo articles
email: NOCOMMENT
description: "This Wenmo articles site... Excited!"
baseurl: ""
url: "https://haplus1s.github.io/"
twitter_username: NOCOMMENT
github_username:  haplus1s

# Build settings
markdown: kramdown
permalink: pretty
